// layout
export const SHOW_MENU = "SHOW_MENU"

// sermons
export const SHOW_SERMONS_FILTER_MENU = "SHOW_SERMONS_FILTER_MENU"
export const SET_SERMON_BOOK_FILTER = "SET_SERMON_BOOK_FILTER"
export const SET_SERMON_SPEAKER_FILTER = "SET_SERMON_SPEAKER_FILTER"
export const SET_SERMON_SEARCH_FILTER = "SET_SERMON_SEARCH_FILTER"
